[package]
name = "tokio-futures-faq"
version = "0.1.0"
authors = ["The Russian Rust Community on Telegram"]
edition = "2018"
publish = false
description = "Collection of examples for tokio&futures russian FAQ"

[dev-dependencies]
bytes = "0.4.11"
futures = "0.1.25"
tokio = "0.1.13"
